export const slideImageHelp = {
  lv: {
    title: 'Slaida bildes prasības',
    specs: 'Ieteicamās specifikācijas:',
    dimensions: 'Izmērs: Minimums 2000px platumā',
    aspectRatio: 'Proporcijas: 4:3 (landscape orientācija)',
    format: 'Formāts: JPG, PNG vai WebP',
    fileSize: 'Faila izmērs: Līdz 5MB',
    guidelines: 'Vadlīnijas:',
    quality: 'Izmantojiet augstas kvalitātes profesionālas fotogrāfijas',
    lighting: 'Nodrošiniet labu apgaismojumu un skaidru fokusu',
    orientation: 'Landscape orientācija (4:3) darbojas vislabāk',
    area: 'Bilde aizpildīs labās puses 4:3 laukumu',
    button: 'Sapratu',
  },
  en: {
    title: 'Slide Image Requirements',
    specs: 'Recommended Specifications:',
    dimensions: 'Dimensions: Minimum 2000px width',
    aspectRatio: 'Aspect Ratio: 4:3 (landscape orientation)',
    format: 'Format: JPG, PNG or WebP',
    fileSize: 'File Size: Under 5MB',
    guidelines: 'Guidelines:',
    quality: 'Use high-quality professional photos',
    lighting: 'Ensure good lighting and clear focus',
    orientation: 'Landscape orientation (4:3) works best',
    area: 'Image will fill the right side 4:3 area',
    button: 'Got it',
  },
}
