/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    sites: Site;
    'power-groups': PowerGroup;
    users: User;
    'site-memberships': SiteMembership;
    media: Media;
    events: Event;
    blog: Blog;
    'special-requests': SpecialRequest;
    top40: Top40;
    top20: Top20;
    'success-stories': SuccessStory;
    'one-to-one-meetings': OneToOneMeeting;
    referrals: Referral;
    'contact-submissions': ContactSubmission;
    'event-submissions': EventSubmission;
    wiki: Wiki;
    'audit-logs': AuditLog;
    'policy-templates': PolicyTemplate;
    'ai-settings': AiSetting;
    'homepage-settings': HomepageSetting;
    'contacts-page-settings': ContactsPageSetting;
    'about-us-settings': AboutUsSetting;
    'faq-settings': FaqSetting;
    'site-settings-collection': SiteSettingsCollection;
    'slideshow-settings-collection': SlideshowSettingsCollection;
    'listing-pages-seo': ListingPagesSeo;
    'companies-page-settings': CompaniesPageSetting;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    sites: SitesSelect<false> | SitesSelect<true>;
    'power-groups': PowerGroupsSelect<false> | PowerGroupsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'site-memberships': SiteMembershipsSelect<false> | SiteMembershipsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
    'special-requests': SpecialRequestsSelect<false> | SpecialRequestsSelect<true>;
    top40: Top40Select<false> | Top40Select<true>;
    top20: Top20Select<false> | Top20Select<true>;
    'success-stories': SuccessStoriesSelect<false> | SuccessStoriesSelect<true>;
    'one-to-one-meetings': OneToOneMeetingsSelect<false> | OneToOneMeetingsSelect<true>;
    referrals: ReferralsSelect<false> | ReferralsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'event-submissions': EventSubmissionsSelect<false> | EventSubmissionsSelect<true>;
    wiki: WikiSelect<false> | WikiSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'policy-templates': PolicyTemplatesSelect<false> | PolicyTemplatesSelect<true>;
    'ai-settings': AiSettingsSelect<false> | AiSettingsSelect<true>;
    'homepage-settings': HomepageSettingsSelect<false> | HomepageSettingsSelect<true>;
    'contacts-page-settings': ContactsPageSettingsSelect<false> | ContactsPageSettingsSelect<true>;
    'about-us-settings': AboutUsSettingsSelect<false> | AboutUsSettingsSelect<true>;
    'faq-settings': FaqSettingsSelect<false> | FaqSettingsSelect<true>;
    'site-settings-collection': SiteSettingsCollectionSelect<false> | SiteSettingsCollectionSelect<true>;
    'slideshow-settings-collection': SlideshowSettingsCollectionSelect<false> | SlideshowSettingsCollectionSelect<true>;
    'listing-pages-seo': ListingPagesSeoSelect<false> | ListingPagesSeoSelect<true>;
    'companies-page-settings': CompaniesPageSettingsSelect<false> | CompaniesPageSettingsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Manage the organisations hosted on this install
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: number;
  /**
   * Organisation name, e.g., "Riga Business Club"
   */
  name: string;
  /**
   * URL-friendly identifier, e.g., "vivaldi"
   */
  slug: string;
  /**
   * Primary domain, e.g., "riga.example.org"
   */
  domain: string;
  status?: ('active' | 'inactive') | null;
  /**
   * Enable 1-2-1 meetings, referrals tracking
   */
  enableActivities?: boolean | null;
  /**
   * Enable onsite/online attendance tracking in slideshow
   */
  enableAttendance?: boolean | null;
  /**
   * Enable success stories feature in profile and global pages
   */
  enableSuccessStories?: boolean | null;
  /**
   * Enable AI chatbot for this chapter (requires global AI Settings to be enabled)
   */
  enableAiChat?: boolean | null;
  /**
   * Show this chapter as a section on the brand-free, token-gated combined special requests page
   */
  includeInSharedRequests?: boolean | null;
  locale?: ('en' | 'lv') | null;
  /**
   * IANA timezone identifier (e.g., Europe/Riga, Europe/London)
   */
  timezone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "power-groups".
 */
export interface PowerGroup {
  id: number;
  /**
   * The organisation this power group belongs to
   */
  site?: (number | null) | Site;
  title: string;
  /**
   * URL-friendly identifier (auto-generated from title if left empty)
   */
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Global user accounts (login credentials)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  surname: string;
  /**
   * Global administrator with access to all sites
   */
  isSuperadmin?: boolean | null;
  customResetToken?: string | null;
  customResetExpiry?: string | null;
  magicLinkToken?: string | null;
  magicLinkExpiry?: string | null;
  pendingEmail?: string | null;
  emailChangeToken?: string | null;
  emailChangeExpiry?: string | null;
  adminHostname?: string | null;
  currentSiteId?: string | null;
  currentMembershipId?: string | null;
  currentRole?: string | null;
  currentStatus?: string | null;
  siteEnableActivities?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * Member profiles for each site
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-memberships".
 */
export interface SiteMembership {
  id: number;
  /**
   * Check to create a new user instead of selecting existing
   */
  createNewUser?: boolean | null;
  /**
   * Email for the new user account
   */
  newUserEmail?: string | null;
  newUserName?: string | null;
  newUserSurname?: string | null;
  /**
   * Select existing user or check "Create New User" above
   */
  user?: (number | null) | User;
  /**
   * The organisation this membership is for
   */
  site?: (number | null) | Site;
  role: 'member' | 'member-admin';
  status: 'active' | 'blocked';
  /**
   * First name (synced with user account)
   */
  name?: string | null;
  /**
   * Last name (synced with user account)
   */
  surname?: string | null;
  /**
   * Contact phone number for this chapter
   */
  phone?: string | null;
  /**
   * Profile photo
   */
  profileImage?: (number | null) | Media;
  description?: string | null;
  logo?: (number | null) | Media;
  /**
   * Image for slideshow presentation (recommended: 4:3 aspect ratio, 2000px width minimum)
   */
  slideImage?: (number | null) | Media;
  /**
   * Background color for slide image area (default: white)
   */
  slideBackgroundColor?: string | null;
  /**
   * How the image should fit in the 4:3 area
   */
  slideImageMode?: ('contain' | 'cover') | null;
  /**
   * Company name
   */
  company?: string | null;
  companyPhone?: string | null;
  companyEmail?: string | null;
  website?: string | null;
  /**
   * Country (searchable). Stored as ISO 3166-1 alpha-2 code, e.g. "LV".
   */
  country?: string | null;
  companyDescription?: string | null;
  /**
   * Add images to showcase your company, portfolio, or offers
   */
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  inaugurationDate?: string | null;
  powerGroup?: (number | null) | PowerGroup;
  jobPosition?: string | null;
  /**
   * Role held in the organisation (e.g., President, Vice President, Treasurer)
   */
  orgRole?: string | null;
  powerGroupLead?: boolean | null;
  /**
   * How this member attends meetings
   */
  attendanceType?: ('onsite' | 'online') | null;
  /**
   * Thank You For Coming Back points received
   */
  tyfcbReceived?: number | null;
  /**
   * Thank You For Coming Back points given
   */
  tyfcbGiven?: number | null;
  /**
   * Total revenue received through the organisation, in EUR
   */
  revenueReceived?: number | null;
  referralsReceivedCount?: number | null;
  referralsGivenCount?: number | null;
  /**
   * Remaining AI chatbot credit in USD
   */
  aiCreditBalanceUsd?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  site?: (number | null) | Site;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * The organisation this event belongs to
   */
  site?: (number | null) | Site;
  title: string;
  slug?: string | null;
  date: string;
  endDate?: string | null;
  location?: string | null;
  description?: {
    [k: string]: unknown;
  };
  image?: (number | null) | Media;
  /**
   * If unchecked, only members can see this event
   */
  isPublic?: boolean | null;
  /**
   * Search engine optimization settings
   */
  seo?: {
    /**
     * Title shown in search results (50-60 characters recommended)
     */
    metaTitle?: string | null;
    /**
     * Description shown in search results (150-160 characters recommended)
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords for SEO (optional, less important for modern SEO)
     */
    keywords?: string | null;
    /**
     * Title for social sharing (max 95 chars). Falls back to Meta Title if empty.
     */
    ogTitle?: string | null;
    /**
     * Description for social sharing (max 300 chars). Falls back to Meta Description if empty.
     */
    ogDescription?: string | null;
    /**
     * Image for social sharing (1200x630px recommended)
     */
    ogImage?: (number | null) | Media;
    /**
     * Override the canonical URL if needed
     */
    canonicalUrl?: string | null;
    /**
     * Hide from search engines
     */
    noIndex?: boolean | null;
    /**
     * Don't follow links
     */
    noFollow?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: number;
  /**
   * The organisation this blog post belongs to
   */
  site?: (number | null) | Site;
  title: string;
  slug?: string | null;
  /**
   * Short summary for listings
   */
  excerpt?: string | null;
  content?: {
    [k: string]: unknown;
  };
  featuredImage?: (number | null) | Media;
  author?: (number | null) | User;
  publishedAt?: string | null;
  /**
   * Search engine optimization settings
   */
  seo?: {
    /**
     * Title shown in search results (50-60 characters recommended)
     */
    metaTitle?: string | null;
    /**
     * Description shown in search results (150-160 characters recommended)
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords for SEO (optional, less important for modern SEO)
     */
    keywords?: string | null;
    /**
     * Title for social sharing (max 95 chars). Falls back to Meta Title if empty.
     */
    ogTitle?: string | null;
    /**
     * Description for social sharing (max 300 chars). Falls back to Meta Description if empty.
     */
    ogDescription?: string | null;
    /**
     * Image for social sharing (1200x630px recommended)
     */
    ogImage?: (number | null) | Media;
    /**
     * Override the canonical URL if needed
     */
    canonicalUrl?: string | null;
    /**
     * Hide from search engines
     */
    noIndex?: boolean | null;
    /**
     * Don't follow links
     */
    noFollow?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "special-requests".
 */
export interface SpecialRequest {
  id: number;
  /**
   * The organisation this request belongs to
   */
  site?: (number | null) | Site;
  /**
   * What are you looking for?
   */
  request: string;
  /**
   * Company registration number if applicable
   */
  registrationNumber?: string | null;
  /**
   * Show this request publicly to other members
   */
  isPublic?: boolean | null;
  requestedBy: number | User;
  status?: ('open' | 'in-progress' | 'fulfilled' | 'closed') | null;
  /**
   * Display order in the member profile list (lower = higher up).
   */
  sortOrder?: number | null;
  /**
   * Feature this request on the slideshow slide (one per member).
   */
  showOnSlide?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "top40".
 */
export interface Top40 {
  id: number;
  /**
   * The organisation this entry belongs to
   */
  site?: (number | null) | Site;
  companyName: string;
  contactPerson: string;
  /**
   * Job title / position
   */
  position?: string | null;
  /**
   * Company registration number
   */
  registrationNumber?: string | null;
  notes?: string | null;
  /**
   * AI-generated business category tags (comma separated)
   */
  businessTags?: string | null;
  submittedBy: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "top20".
 */
export interface Top20 {
  id: number;
  /**
   * The organisation this entry belongs to
   */
  site?: (number | null) | Site;
  companyName: string;
  contactPerson?: string | null;
  /**
   * Job title / position
   */
  position?: string | null;
  /**
   * Company registration number
   */
  registrationNumber?: string | null;
  notes?: string | null;
  /**
   * AI-generated business category tags (comma separated)
   */
  businessTags?: string | null;
  submittedBy: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "success-stories".
 */
export interface SuccessStory {
  id: number;
  /**
   * The organisation this story belongs to
   */
  site?: (number | null) | Site;
  /**
   * Success story title
   */
  title: string;
  /**
   * Describe your success story
   */
  story: string;
  /**
   * Business value generated (e.g., "€5,000")
   */
  businessValue?: string | null;
  /**
   * The member who helped with this success
   */
  partnerMember?: (number | null) | User;
  /**
   * Show this story publicly to other members
   */
  isPublic?: boolean | null;
  author: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "one-to-one-meetings".
 */
export interface OneToOneMeeting {
  id: number;
  /**
   * The organisation this meeting belongs to
   */
  site?: (number | null) | Site;
  /**
   * The member you met with
   */
  metWith: number | User;
  /**
   * Who invited to the meeting
   */
  invitedBy: number | User;
  /**
   * Meeting location
   */
  location: string;
  /**
   * Topics of conversation
   */
  topics: string;
  date: string;
  /**
   * Comments from both participants
   */
  comments?:
    | {
        text: string;
        author: number | User;
        commentCreatedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Meeting creator (can edit/delete)
   */
  createdBy: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referrals".
 */
export interface Referral {
  id: number;
  /**
   * The organisation this referral belongs to
   */
  site?: (number | null) | Site;
  /**
   * Who gave the referral
   */
  fromUser: number | User;
  /**
   * Who received the referral
   */
  toUser: number | User;
  date: string;
  /**
   * Description of the referral
   */
  description: string;
  /**
   * Referral outcome status
   */
  status: 'pending' | 'success' | 'failed';
  /**
   * Business value in EUR (only for successful referrals)
   */
  value?: number | null;
  /**
   * Referral creator (can edit/delete)
   */
  createdBy: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  /**
   * The organisation this submission belongs to
   */
  site?: (number | null) | Site;
  name: string;
  email: string;
  phone?: string | null;
  subject: string;
  message: string;
  status?: ('new' | 'in-progress' | 'resolved') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-submissions".
 */
export interface EventSubmission {
  id: number;
  /**
   * The organisation this submission belongs to
   */
  site?: (number | null) | Site;
  /**
   * Cleared automatically if the event is deleted
   */
  event?: (number | null) | Event;
  /**
   * Snapshot of the event title — kept even after the event is deleted
   */
  eventTitle?: string | null;
  /**
   * Full name of the person registering
   */
  name: string;
  email: string;
  /**
   * Optional phone number
   */
  phone?: string | null;
  /**
   * Optional company name
   */
  company?: string | null;
  /**
   * Optional — who invited the registrant
   */
  invitedBy?: string | null;
  /**
   * Optional message or questions
   */
  message?: string | null;
  status?: ('pending' | 'confirmed' | 'cancelled') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wiki".
 */
export interface Wiki {
  id: number;
  /**
   * The organisation this page belongs to
   */
  site?: (number | null) | Site;
  title: string;
  slug: string;
  content?: {
    [k: string]: unknown;
  };
  layout?:
    | (
        | {
            heading: string;
            subheading?: string | null;
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content?: {
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'content-section';
          }
        | {
            heading?: string | null;
            members?: (number | SiteMembership)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'team-grid';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  question: string;
                  answer: {
                    [k: string]: unknown;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            heading?: string | null;
            email?: string | null;
            phone?: string | null;
            address?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact-info';
          }
      )[]
    | null;
  /**
   * Search engine optimization settings
   */
  seo?: {
    /**
     * Title shown in search results (50-60 characters recommended)
     */
    metaTitle?: string | null;
    /**
     * Description shown in search results (150-160 characters recommended)
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords for SEO (optional, less important for modern SEO)
     */
    keywords?: string | null;
    /**
     * Title for social sharing (max 95 chars). Falls back to Meta Title if empty.
     */
    ogTitle?: string | null;
    /**
     * Description for social sharing (max 300 chars). Falls back to Meta Description if empty.
     */
    ogDescription?: string | null;
    /**
     * Image for social sharing (1200x630px recommended)
     */
    ogImage?: (number | null) | Media;
    /**
     * Override the canonical URL if needed
     */
    canonicalUrl?: string | null;
    /**
     * Hide from search engines
     */
    noIndex?: boolean | null;
    /**
     * Don't follow links
     */
    noFollow?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Security audit trail - automatically cleaned after 1 month
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  /**
   * Type of action performed
   */
  action:
    | 'user_deleted'
    | 'user_created'
    | 'user_updated'
    | 'superadmin_login'
    | 'superadmin_login_failed'
    | 'membership_created'
    | 'membership_deleted'
    | 'site_created'
    | 'site_deleted';
  /**
   * User who performed the action
   */
  performedBy?: (number | null) | User;
  /**
   * Email of user (preserved if user is deleted)
   */
  performedByEmail?: string | null;
  /**
   * Type of entity affected
   */
  targetType?: ('user' | 'site' | 'membership') | null;
  /**
   * ID of the affected entity
   */
  targetId?: string | null;
  /**
   * Email of affected user (if applicable)
   */
  targetEmail?: string | null;
  /**
   * Additional action details
   */
  details?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * IP address of the request
   */
  ipAddress?: string | null;
  /**
   * User agent string
   */
  userAgent?: string | null;
  /**
   * When this log entry should be deleted (1 month from creation)
   */
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Universal policy templates shared across all sites. Use placeholders like {site-name}, {site-email}, {site-domain}.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policy-templates".
 */
export interface PolicyTemplate {
  id: number;
  /**
   * Type of policy document
   */
  type: 'terms' | 'privacy' | 'cookies';
  /**
   * Language of this policy template
   */
  locale: 'lv' | 'en';
  /**
   * Policy title (e.g., "Lietošanas noteikumi" or "Terms and Conditions")
   */
  title: string;
  /**
   * Policy content. Available placeholders: {site-name}, {site-email}, {site-domain}, {current-date}, {last-updated}
   */
  content: string;
  /**
   * When this policy was last updated
   */
  lastUpdated?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Configure AI chatbot settings (OpenAI API key, model, system prompt)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-settings".
 */
export interface AiSetting {
  id: number;
  /**
   * Internal label for this configuration
   */
  label: string;
  /**
   * Master switch to enable/disable the AI chatbot across all sites
   */
  enabled?: boolean | null;
  /**
   * OpenAI API key (stored in database, never exposed to client)
   */
  openaiApiKey: string;
  /**
   * Perplexity API key for Top40 business tag generation
   */
  perplexityApiKey?: string | null;
  /**
   * Perplexity model for tag generation
   */
  perplexityModel?: ('sonar-pro' | 'sonar') | null;
  /**
   * Default OpenAI model for chat (price: input/output per 1M tokens)
   */
  model:
    | 'gpt-4.1-nano'
    | 'gpt-4o-mini'
    | 'gpt-4.1-mini'
    | 'o3-mini'
    | 'o4-mini'
    | 'gpt-5'
    | 'o3'
    | 'gpt-4.1'
    | 'gpt-4o';
  /**
   * System prompt defining the assistant behaviour and which topics it will answer
   */
  systemPrompt: string;
  /**
   * Maximum tokens in AI response (100-4096)
   */
  maxTokens: number;
  /**
   * Response creativity (0 = deterministic, 2 = very creative). Recommended: 0.7
   */
  temperature: number;
  /**
   * Default AI credit balance in USD for members (e.g., 10.00 = $10). Set on each site-membership manually.
   */
  defaultAiCreditUsd: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Edit the homepage hero section, statistics, and call-to-action.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-settings".
 */
export interface HomepageSetting {
  id: number;
  site: number | Site;
  internalTitle?: string | null;
  hero: {
    /**
     * The main headline displayed in the hero
     */
    title: string;
    /**
     * This word will appear in red within the title
     */
    highlightedText?: string | null;
    /**
     * Supporting text below the main title
     */
    description?: string | null;
    primaryButtonText?: string | null;
    primaryButtonLink?: string | null;
    secondaryButtonText?: string | null;
    secondaryButtonLink?: string | null;
    /**
     * Optional background image for the hero section
     */
    backgroundImage?: (number | null) | Media;
    /**
     * Add a dark overlay over the background image to improve text readability
     */
    enableOverlay?: boolean | null;
  };
  stats?: {
    title?: string | null;
    /**
     * Add up to 6 statistics. They display in 2 rows of 3 on desktop.
     */
    items?:
      | {
          /**
           * Iconify icon name (browse at https://icon-sets.iconify.design/)
           */
          icon?: string | null;
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  cta?: {
    title?: string | null;
    description?: string | null;
    buttonText?: string | null;
    buttonLink?: string | null;
  };
  /**
   * Search engine optimization settings
   */
  seo?: {
    /**
     * Title shown in search results (50-60 characters recommended)
     */
    metaTitle?: string | null;
    /**
     * Description shown in search results (150-160 characters recommended)
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords for SEO (optional, less important for modern SEO)
     */
    keywords?: string | null;
    /**
     * Title for social sharing (max 95 chars). Falls back to Meta Title if empty.
     */
    ogTitle?: string | null;
    /**
     * Description for social sharing (max 300 chars). Falls back to Meta Description if empty.
     */
    ogDescription?: string | null;
    /**
     * Image for social sharing (1200x630px recommended)
     */
    ogImage?: (number | null) | Media;
    /**
     * Override the canonical URL if needed
     */
    canonicalUrl?: string | null;
    /**
     * Hide from search engines
     */
    noIndex?: boolean | null;
    /**
     * Don't follow links
     */
    noFollow?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts-page-settings".
 */
export interface ContactsPageSetting {
  id: number;
  site: number | Site;
  title: string;
  /**
   * Select members to display as contact persons
   */
  contactPersons?:
    | {
        /**
         * Select a member from your chapter
         */
        member: number | SiteMembership;
        id?: string | null;
      }[]
    | null;
  formSettings: {
    formTitle: string;
    formDescription?: string | null;
    submitButtonText: string;
    successMessage: string;
  };
  /**
   * Search engine optimization settings
   */
  seo?: {
    /**
     * Title shown in search results (50-60 characters recommended)
     */
    metaTitle?: string | null;
    /**
     * Description shown in search results (150-160 characters recommended)
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords for SEO (optional, less important for modern SEO)
     */
    keywords?: string | null;
    /**
     * Title for social sharing (max 95 chars). Falls back to Meta Title if empty.
     */
    ogTitle?: string | null;
    /**
     * Description for social sharing (max 300 chars). Falls back to Meta Description if empty.
     */
    ogDescription?: string | null;
    /**
     * Image for social sharing (1200x630px recommended)
     */
    ogImage?: (number | null) | Media;
    /**
     * Override the canonical URL if needed
     */
    canonicalUrl?: string | null;
    /**
     * Hide from search engines
     */
    noIndex?: boolean | null;
    /**
     * Don't follow links
     */
    noFollow?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us-settings".
 */
export interface AboutUsSetting {
  id: number;
  site: number | Site;
  title: string;
  /**
   * General description of your organisation
   */
  introduction: string;
  /**
   * Select members from your chapter to display as leadership team
   */
  chapterLeaders?:
    | {
        /**
         * Select a member from your chapter
         */
        member: number | User;
        /**
         * e.g., President, Vice President, Secretary/Treasurer
         */
        position: string;
        id?: string | null;
      }[]
    | null;
  howWeWork?: {
    title?: string | null;
    /**
     * Describe how your organisation operates and its methodology
     */
    description?: string | null;
    /**
     * Add up to 4 weekly meetings
     */
    meetings?:
      | {
          /**
           * How often do you meet?
           */
          frequency: string;
          time: string;
          /**
           * Meeting venue address
           */
          location?: string | null;
          isVirtual?: boolean | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Key principles your organisation follows
   */
  principles?:
    | {
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  membershipInfo?: {
    title?: string | null;
    /**
     * Information about becoming a member
     */
    description?: string | null;
    benefits?:
      | {
          benefit: string;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Search engine optimization settings
   */
  seo?: {
    /**
     * Title shown in search results (50-60 characters recommended)
     */
    metaTitle?: string | null;
    /**
     * Description shown in search results (150-160 characters recommended)
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords for SEO (optional, less important for modern SEO)
     */
    keywords?: string | null;
    /**
     * Title for social sharing (max 95 chars). Falls back to Meta Title if empty.
     */
    ogTitle?: string | null;
    /**
     * Description for social sharing (max 300 chars). Falls back to Meta Description if empty.
     */
    ogDescription?: string | null;
    /**
     * Image for social sharing (1200x630px recommended)
     */
    ogImage?: (number | null) | Media;
    /**
     * Override the canonical URL if needed
     */
    canonicalUrl?: string | null;
    /**
     * Hide from search engines
     */
    noIndex?: boolean | null;
    /**
     * Don't follow links
     */
    noFollow?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-settings".
 */
export interface FaqSetting {
  id: number;
  site: number | Site;
  pageTitle: string;
  pageDescription?: string | null;
  faqs?:
    | {
        question: string;
        answer: {
          [k: string]: unknown;
        };
        category?: ('general' | 'membership' | 'meetings' | 'referrals' | 'events' | 'other') | null;
        /**
         * Lower numbers appear first
         */
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Search engine optimization settings
   */
  seo?: {
    /**
     * Title shown in search results (50-60 characters recommended)
     */
    metaTitle?: string | null;
    /**
     * Description shown in search results (150-160 characters recommended)
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords for SEO (optional, less important for modern SEO)
     */
    keywords?: string | null;
    /**
     * Title for social sharing (max 95 chars). Falls back to Meta Title if empty.
     */
    ogTitle?: string | null;
    /**
     * Description for social sharing (max 300 chars). Falls back to Meta Description if empty.
     */
    ogDescription?: string | null;
    /**
     * Image for social sharing (1200x630px recommended)
     */
    ogImage?: (number | null) | Media;
    /**
     * Override the canonical URL if needed
     */
    canonicalUrl?: string | null;
    /**
     * Hide from search engines
     */
    noIndex?: boolean | null;
    /**
     * Don't follow links
     */
    noFollow?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Configure site-wide settings including branding, contact information, and social media.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings-collection".
 */
export interface SiteSettingsCollection {
  id: number;
  site: number | Site;
  internalTitle?: string | null;
  /**
   * The name of your site displayed in the browser and header
   */
  siteName: string;
  /**
   * Main logo displayed in the header (recommended: SVG or PNG with transparent background)
   */
  siteLogo?: (number | null) | Media;
  /**
   * Small favicon for browser tabs (16x16 PNG)
   */
  favicon16?: (number | null) | Media;
  /**
   * Standard favicon for browser tabs (32x32 PNG)
   */
  favicon32?: (number | null) | Media;
  /**
   * Icon for iOS devices when site is saved to home screen (180x180 PNG)
   */
  appleTouchIcon?: (number | null) | Media;
  /**
   * Icon for Android devices (192x192 PNG)
   */
  favicon192?: (number | null) | Media;
  /**
   * Large icon for Android devices (512x512 PNG)
   */
  favicon512?: (number | null) | Media;
  /**
   * Email addresses that will receive form submissions and notifications
   */
  adminEmails?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Email address used as sender for all outgoing emails (notifications, password resets, etc.)
   */
  emailFrom: string;
  /**
   * Display name shown as sender for all outgoing emails
   */
  emailFromName: string;
  socialMedia?: {
    /**
     * Full URL to your Facebook page
     */
    facebook?: string | null;
    /**
     * Full URL to your Instagram profile
     */
    instagram?: string | null;
    /**
     * Full URL to your Twitter/X profile
     */
    twitter?: string | null;
    /**
     * Full URL to your LinkedIn page
     */
    linkedin?: string | null;
    /**
     * Full URL to your TikTok profile
     */
    tiktok?: string | null;
  };
  /**
   * Your Google Analytics 4 Measurement ID (starts with G-)
   */
  googleAnalyticsId?: string | null;
  /**
   * Your Google Tag Manager Container ID (starts with GTM-)
   */
  googleTagManagerId?: string | null;
  /**
   * Your Facebook Pixel ID (numeric)
   */
  facebookPixelId?: string | null;
  /**
   * Default SEO settings for the entire site
   */
  seo?: {
    /**
     * Used when page has no custom title
     */
    defaultTitle?: string | null;
    /**
     * Appended to page titles (e.g., " | Riga Business Club")
     */
    titleSuffix?: string | null;
    /**
     * Used when page has no custom description
     */
    defaultDescription?: string | null;
    /**
     * Site-wide keywords (comma-separated)
     */
    defaultKeywords?: string | null;
    /**
     * Site name for social sharing
     */
    ogSiteName?: string | null;
    /**
     * Default image for social sharing when page has no image (1200x630px)
     */
    defaultOgImage?: (number | null) | Media;
    twitterCard?: ('summary' | 'summary_large_image') | null;
    /**
     * X / Twitter account for the site (e.g., @rigabusiness)
     */
    twitterSite?: string | null;
    /**
     * Google Search Console verification code
     */
    googleVerification?: string | null;
    /**
     * Bing Webmaster Tools verification code
     */
    bingVerification?: string | null;
    /**
     * Custom robots.txt content (leave empty for default)
     */
    robotsTxt?: string | null;
  };
  /**
   * Schema.org structured data for rich snippets
   */
  schema?: {
    organizationType?: ('Organization' | 'LocalBusiness' | 'ProfessionalService' | 'Corporation') | null;
    /**
     * Legal name of the organization
     */
    organizationName?: string | null;
    /**
     * Logo for schema.org (min 112x112px, recommended 1200x630px)
     */
    organizationLogo?: (number | null) | Media;
    foundingDate?: string | null;
    address?: {
      streetAddress?: string | null;
      city?: string | null;
      postalCode?: string | null;
      country?: string | null;
    };
    contactPhone?: string | null;
    contactEmail?: string | null;
    /**
     * Links to social media profiles for schema.org
     */
    sameAs?:
      | {
          url: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slideshow-settings-collection".
 */
export interface SlideshowSettingsCollection {
  id: number;
  site: number | Site;
  internalTitle?: string | null;
  /**
   * How long each slide is displayed
   */
  slideSeconds: number;
  /**
   * Speech Master slide duration = slideSeconds × this value
   */
  speechMasterMultiplier?: number | null;
  /**
   * Members whose given business is below this amount will not show the row on their slide. 0 = always show.
   */
  businessGivenMin?: number | null;
  /**
   * Members whose received business is below this amount will not show the row on their slide. 0 = always show.
   */
  businessReceivedMin?: number | null;
  /**
   * Drag to reorder; mix any block types freely.
   */
  slides?:
    | (
        | {
            /**
             * Optional title shown above the logo grid
             */
            title?: string | null;
            /**
             * Override slide duration (leave empty to use default)
             */
            customSlideSeconds?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'logoWall';
          }
        | {
            /**
             * Member to display with crown icon. Default duration uses speechMasterMultiplier.
             */
            member: number | SiteMembership;
            /**
             * Override slide duration (leave empty to use default)
             */
            customSlideSeconds?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'speechMaster';
          }
        | {
            /**
             * Override the default "Runas Meistars" title shown above the photo
             */
            title?: string | null;
            member: number | SiteMembership;
            /**
             * Override slide duration (leave empty to use default)
             */
            customSlideSeconds?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'speechMasterCeremony';
          }
        | {
            powerGroup: number | PowerGroup;
            /**
             * Disable auto-advance timer for this group's slides
             */
            disableTimer?: boolean | null;
            /**
             * Override slide duration (leave empty to use default)
             */
            customSlideSeconds?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'powerGroup';
          }
        | {
            /**
             * Section title shown above guest list (e.g., "Topošie biedri")
             */
            title?: string | null;
            /**
             * One guest per line: Name, Company, Description (comma-separated). Optional sub-section markers: #Online, #Onsite (case-insensitive).
             */
            guestsText: string;
            /**
             * Override slide duration (leave empty to use default)
             */
            customSlideSeconds?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'guests';
          }
        | {
            image: number | Media;
            displayMode?: ('contain' | 'cover') | null;
            /**
             * Background color visible in letterbox area
             */
            backgroundColor?: string | null;
            /**
             * Override slide duration (leave empty to use default)
             */
            customSlideSeconds?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'customImage';
          }
      )[]
    | null;
  /**
   * Members to skip from slideshow (e.g., absent members)
   */
  skipMembers?: (number | SiteMembership)[] | null;
  /**
   * MP3 file that plays on the last second of each member slide
   */
  transitionSound?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Configure SEO settings for listing pages (Blog, Events, Companies, Success Stories)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-pages-seo".
 */
export interface ListingPagesSeo {
  id: number;
  site: number | Site;
  title?: string | null;
  blogPage?: {
    /**
     * Title shown in browser tab and search results
     */
    pageTitle?: string | null;
    /**
     * Description for search engines
     */
    pageDescription?: string | null;
    /**
     * Search engine optimization settings
     */
    seo?: {
      /**
       * Title shown in search results (50-60 characters recommended)
       */
      metaTitle?: string | null;
      /**
       * Description shown in search results (150-160 characters recommended)
       */
      metaDescription?: string | null;
      /**
       * Comma-separated keywords for SEO (optional, less important for modern SEO)
       */
      keywords?: string | null;
      /**
       * Title for social sharing (max 95 chars). Falls back to Meta Title if empty.
       */
      ogTitle?: string | null;
      /**
       * Description for social sharing (max 300 chars). Falls back to Meta Description if empty.
       */
      ogDescription?: string | null;
      /**
       * Image for social sharing (1200x630px recommended)
       */
      ogImage?: (number | null) | Media;
      /**
       * Override the canonical URL if needed
       */
      canonicalUrl?: string | null;
      /**
       * Hide from search engines
       */
      noIndex?: boolean | null;
      /**
       * Don't follow links
       */
      noFollow?: boolean | null;
    };
  };
  eventsPage?: {
    /**
     * Title shown in browser tab and search results
     */
    pageTitle?: string | null;
    /**
     * Description for search engines
     */
    pageDescription?: string | null;
    /**
     * Search engine optimization settings
     */
    seo?: {
      /**
       * Title shown in search results (50-60 characters recommended)
       */
      metaTitle?: string | null;
      /**
       * Description shown in search results (150-160 characters recommended)
       */
      metaDescription?: string | null;
      /**
       * Comma-separated keywords for SEO (optional, less important for modern SEO)
       */
      keywords?: string | null;
      /**
       * Title for social sharing (max 95 chars). Falls back to Meta Title if empty.
       */
      ogTitle?: string | null;
      /**
       * Description for social sharing (max 300 chars). Falls back to Meta Description if empty.
       */
      ogDescription?: string | null;
      /**
       * Image for social sharing (1200x630px recommended)
       */
      ogImage?: (number | null) | Media;
      /**
       * Override the canonical URL if needed
       */
      canonicalUrl?: string | null;
      /**
       * Hide from search engines
       */
      noIndex?: boolean | null;
      /**
       * Don't follow links
       */
      noFollow?: boolean | null;
    };
  };
  companiesPage?: {
    /**
     * Title shown in browser tab and search results
     */
    pageTitle?: string | null;
    /**
     * Description for search engines
     */
    pageDescription?: string | null;
    /**
     * Search engine optimization settings
     */
    seo?: {
      /**
       * Title shown in search results (50-60 characters recommended)
       */
      metaTitle?: string | null;
      /**
       * Description shown in search results (150-160 characters recommended)
       */
      metaDescription?: string | null;
      /**
       * Comma-separated keywords for SEO (optional, less important for modern SEO)
       */
      keywords?: string | null;
      /**
       * Title for social sharing (max 95 chars). Falls back to Meta Title if empty.
       */
      ogTitle?: string | null;
      /**
       * Description for social sharing (max 300 chars). Falls back to Meta Description if empty.
       */
      ogDescription?: string | null;
      /**
       * Image for social sharing (1200x630px recommended)
       */
      ogImage?: (number | null) | Media;
      /**
       * Override the canonical URL if needed
       */
      canonicalUrl?: string | null;
      /**
       * Hide from search engines
       */
      noIndex?: boolean | null;
      /**
       * Don't follow links
       */
      noFollow?: boolean | null;
    };
  };
  successStoriesPage?: {
    /**
     * Title shown in browser tab and search results
     */
    pageTitle?: string | null;
    /**
     * Description for search engines
     */
    pageDescription?: string | null;
    /**
     * Search engine optimization settings
     */
    seo?: {
      /**
       * Title shown in search results (50-60 characters recommended)
       */
      metaTitle?: string | null;
      /**
       * Description shown in search results (150-160 characters recommended)
       */
      metaDescription?: string | null;
      /**
       * Comma-separated keywords for SEO (optional, less important for modern SEO)
       */
      keywords?: string | null;
      /**
       * Title for social sharing (max 95 chars). Falls back to Meta Title if empty.
       */
      ogTitle?: string | null;
      /**
       * Description for social sharing (max 300 chars). Falls back to Meta Description if empty.
       */
      ogDescription?: string | null;
      /**
       * Image for social sharing (1200x630px recommended)
       */
      ogImage?: (number | null) | Media;
      /**
       * Override the canonical URL if needed
       */
      canonicalUrl?: string | null;
      /**
       * Hide from search engines
       */
      noIndex?: boolean | null;
      /**
       * Don't follow links
       */
      noFollow?: boolean | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies-page-settings".
 */
export interface CompaniesPageSetting {
  id: number;
  site: number | Site;
  title: string;
  /**
   * Heading displayed above the description text
   */
  subtitle?: string | null;
  /**
   * Descriptive text shown below the subtitle
   */
  description?: string | null;
  /**
   * Text on the call-to-action button
   */
  ctaLabel?: string | null;
  /**
   * URL the button links to (e.g., /contacts)
   */
  ctaLink?: string | null;
  /**
   * Search engine optimization settings
   */
  seo?: {
    /**
     * Title shown in search results (50-60 characters recommended)
     */
    metaTitle?: string | null;
    /**
     * Description shown in search results (150-160 characters recommended)
     */
    metaDescription?: string | null;
    /**
     * Comma-separated keywords for SEO (optional, less important for modern SEO)
     */
    keywords?: string | null;
    /**
     * Title for social sharing (max 95 chars). Falls back to Meta Title if empty.
     */
    ogTitle?: string | null;
    /**
     * Description for social sharing (max 300 chars). Falls back to Meta Description if empty.
     */
    ogDescription?: string | null;
    /**
     * Image for social sharing (1200x630px recommended)
     */
    ogImage?: (number | null) | Media;
    /**
     * Override the canonical URL if needed
     */
    canonicalUrl?: string | null;
    /**
     * Hide from search engines
     */
    noIndex?: boolean | null;
    /**
     * Don't follow links
     */
    noFollow?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'sites';
        value: number | Site;
      } | null)
    | ({
        relationTo: 'power-groups';
        value: number | PowerGroup;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'site-memberships';
        value: number | SiteMembership;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'blog';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'special-requests';
        value: number | SpecialRequest;
      } | null)
    | ({
        relationTo: 'top40';
        value: number | Top40;
      } | null)
    | ({
        relationTo: 'top20';
        value: number | Top20;
      } | null)
    | ({
        relationTo: 'success-stories';
        value: number | SuccessStory;
      } | null)
    | ({
        relationTo: 'one-to-one-meetings';
        value: number | OneToOneMeeting;
      } | null)
    | ({
        relationTo: 'referrals';
        value: number | Referral;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'event-submissions';
        value: number | EventSubmission;
      } | null)
    | ({
        relationTo: 'wiki';
        value: number | Wiki;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'policy-templates';
        value: number | PolicyTemplate;
      } | null)
    | ({
        relationTo: 'ai-settings';
        value: number | AiSetting;
      } | null)
    | ({
        relationTo: 'homepage-settings';
        value: number | HomepageSetting;
      } | null)
    | ({
        relationTo: 'contacts-page-settings';
        value: number | ContactsPageSetting;
      } | null)
    | ({
        relationTo: 'about-us-settings';
        value: number | AboutUsSetting;
      } | null)
    | ({
        relationTo: 'faq-settings';
        value: number | FaqSetting;
      } | null)
    | ({
        relationTo: 'site-settings-collection';
        value: number | SiteSettingsCollection;
      } | null)
    | ({
        relationTo: 'slideshow-settings-collection';
        value: number | SlideshowSettingsCollection;
      } | null)
    | ({
        relationTo: 'listing-pages-seo';
        value: number | ListingPagesSeo;
      } | null)
    | ({
        relationTo: 'companies-page-settings';
        value: number | CompaniesPageSetting;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  domain?: T;
  status?: T;
  enableActivities?: T;
  enableAttendance?: T;
  enableSuccessStories?: T;
  enableAiChat?: T;
  includeInSharedRequests?: T;
  locale?: T;
  timezone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "power-groups_select".
 */
export interface PowerGroupsSelect<T extends boolean = true> {
  site?: T;
  title?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  surname?: T;
  isSuperadmin?: T;
  customResetToken?: T;
  customResetExpiry?: T;
  magicLinkToken?: T;
  magicLinkExpiry?: T;
  pendingEmail?: T;
  emailChangeToken?: T;
  emailChangeExpiry?: T;
  adminHostname?: T;
  currentSiteId?: T;
  currentMembershipId?: T;
  currentRole?: T;
  currentStatus?: T;
  siteEnableActivities?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-memberships_select".
 */
export interface SiteMembershipsSelect<T extends boolean = true> {
  createNewUser?: T;
  newUserEmail?: T;
  newUserName?: T;
  newUserSurname?: T;
  user?: T;
  site?: T;
  role?: T;
  status?: T;
  name?: T;
  surname?: T;
  phone?: T;
  profileImage?: T;
  description?: T;
  logo?: T;
  slideImage?: T;
  slideBackgroundColor?: T;
  slideImageMode?: T;
  company?: T;
  companyPhone?: T;
  companyEmail?: T;
  website?: T;
  country?: T;
  companyDescription?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  inaugurationDate?: T;
  powerGroup?: T;
  jobPosition?: T;
  orgRole?: T;
  powerGroupLead?: T;
  attendanceType?: T;
  tyfcbReceived?: T;
  tyfcbGiven?: T;
  revenueReceived?: T;
  referralsReceivedCount?: T;
  referralsGivenCount?: T;
  aiCreditBalanceUsd?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  site?: T;
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  site?: T;
  title?: T;
  slug?: T;
  date?: T;
  endDate?: T;
  location?: T;
  description?: T;
  image?: T;
  isPublic?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  site?: T;
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  author?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "special-requests_select".
 */
export interface SpecialRequestsSelect<T extends boolean = true> {
  site?: T;
  request?: T;
  registrationNumber?: T;
  isPublic?: T;
  requestedBy?: T;
  status?: T;
  sortOrder?: T;
  showOnSlide?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "top40_select".
 */
export interface Top40Select<T extends boolean = true> {
  site?: T;
  companyName?: T;
  contactPerson?: T;
  position?: T;
  registrationNumber?: T;
  notes?: T;
  businessTags?: T;
  submittedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "top20_select".
 */
export interface Top20Select<T extends boolean = true> {
  site?: T;
  companyName?: T;
  contactPerson?: T;
  position?: T;
  registrationNumber?: T;
  notes?: T;
  businessTags?: T;
  submittedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "success-stories_select".
 */
export interface SuccessStoriesSelect<T extends boolean = true> {
  site?: T;
  title?: T;
  story?: T;
  businessValue?: T;
  partnerMember?: T;
  isPublic?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "one-to-one-meetings_select".
 */
export interface OneToOneMeetingsSelect<T extends boolean = true> {
  site?: T;
  metWith?: T;
  invitedBy?: T;
  location?: T;
  topics?: T;
  date?: T;
  comments?:
    | T
    | {
        text?: T;
        author?: T;
        commentCreatedAt?: T;
        id?: T;
      };
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referrals_select".
 */
export interface ReferralsSelect<T extends boolean = true> {
  site?: T;
  fromUser?: T;
  toUser?: T;
  date?: T;
  description?: T;
  status?: T;
  value?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  site?: T;
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-submissions_select".
 */
export interface EventSubmissionsSelect<T extends boolean = true> {
  site?: T;
  event?: T;
  eventTitle?: T;
  name?: T;
  email?: T;
  phone?: T;
  company?: T;
  invitedBy?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wiki_select".
 */
export interface WikiSelect<T extends boolean = true> {
  site?: T;
  title?: T;
  slug?: T;
  content?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        'content-section'?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        'team-grid'?:
          | T
          | {
              heading?: T;
              members?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'contact-info'?:
          | T
          | {
              heading?: T;
              email?: T;
              phone?: T;
              address?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  action?: T;
  performedBy?: T;
  performedByEmail?: T;
  targetType?: T;
  targetId?: T;
  targetEmail?: T;
  details?: T;
  ipAddress?: T;
  userAgent?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policy-templates_select".
 */
export interface PolicyTemplatesSelect<T extends boolean = true> {
  type?: T;
  locale?: T;
  title?: T;
  content?: T;
  lastUpdated?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-settings_select".
 */
export interface AiSettingsSelect<T extends boolean = true> {
  label?: T;
  enabled?: T;
  openaiApiKey?: T;
  perplexityApiKey?: T;
  perplexityModel?: T;
  model?: T;
  systemPrompt?: T;
  maxTokens?: T;
  temperature?: T;
  defaultAiCreditUsd?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-settings_select".
 */
export interface HomepageSettingsSelect<T extends boolean = true> {
  site?: T;
  internalTitle?: T;
  hero?:
    | T
    | {
        title?: T;
        highlightedText?: T;
        description?: T;
        primaryButtonText?: T;
        primaryButtonLink?: T;
        secondaryButtonText?: T;
        secondaryButtonLink?: T;
        backgroundImage?: T;
        enableOverlay?: T;
      };
  stats?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              icon?: T;
              value?: T;
              label?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        title?: T;
        description?: T;
        buttonText?: T;
        buttonLink?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts-page-settings_select".
 */
export interface ContactsPageSettingsSelect<T extends boolean = true> {
  site?: T;
  title?: T;
  contactPersons?:
    | T
    | {
        member?: T;
        id?: T;
      };
  formSettings?:
    | T
    | {
        formTitle?: T;
        formDescription?: T;
        submitButtonText?: T;
        successMessage?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-us-settings_select".
 */
export interface AboutUsSettingsSelect<T extends boolean = true> {
  site?: T;
  title?: T;
  introduction?: T;
  chapterLeaders?:
    | T
    | {
        member?: T;
        position?: T;
        id?: T;
      };
  howWeWork?:
    | T
    | {
        title?: T;
        description?: T;
        meetings?:
          | T
          | {
              frequency?: T;
              time?: T;
              location?: T;
              isVirtual?: T;
              id?: T;
            };
      };
  principles?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  membershipInfo?:
    | T
    | {
        title?: T;
        description?: T;
        benefits?:
          | T
          | {
              benefit?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-settings_select".
 */
export interface FaqSettingsSelect<T extends boolean = true> {
  site?: T;
  pageTitle?: T;
  pageDescription?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        category?: T;
        order?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings-collection_select".
 */
export interface SiteSettingsCollectionSelect<T extends boolean = true> {
  site?: T;
  internalTitle?: T;
  siteName?: T;
  siteLogo?: T;
  favicon16?: T;
  favicon32?: T;
  appleTouchIcon?: T;
  favicon192?: T;
  favicon512?: T;
  adminEmails?:
    | T
    | {
        email?: T;
        id?: T;
      };
  emailFrom?: T;
  emailFromName?: T;
  socialMedia?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        twitter?: T;
        linkedin?: T;
        tiktok?: T;
      };
  googleAnalyticsId?: T;
  googleTagManagerId?: T;
  facebookPixelId?: T;
  seo?:
    | T
    | {
        defaultTitle?: T;
        titleSuffix?: T;
        defaultDescription?: T;
        defaultKeywords?: T;
        ogSiteName?: T;
        defaultOgImage?: T;
        twitterCard?: T;
        twitterSite?: T;
        googleVerification?: T;
        bingVerification?: T;
        robotsTxt?: T;
      };
  schema?:
    | T
    | {
        organizationType?: T;
        organizationName?: T;
        organizationLogo?: T;
        foundingDate?: T;
        address?:
          | T
          | {
              streetAddress?: T;
              city?: T;
              postalCode?: T;
              country?: T;
            };
        contactPhone?: T;
        contactEmail?: T;
        sameAs?:
          | T
          | {
              url?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "slideshow-settings-collection_select".
 */
export interface SlideshowSettingsCollectionSelect<T extends boolean = true> {
  site?: T;
  internalTitle?: T;
  slideSeconds?: T;
  speechMasterMultiplier?: T;
  businessGivenMin?: T;
  businessReceivedMin?: T;
  slides?:
    | T
    | {
        logoWall?:
          | T
          | {
              title?: T;
              customSlideSeconds?: T;
              id?: T;
              blockName?: T;
            };
        speechMaster?:
          | T
          | {
              member?: T;
              customSlideSeconds?: T;
              id?: T;
              blockName?: T;
            };
        speechMasterCeremony?:
          | T
          | {
              title?: T;
              member?: T;
              customSlideSeconds?: T;
              id?: T;
              blockName?: T;
            };
        powerGroup?:
          | T
          | {
              powerGroup?: T;
              disableTimer?: T;
              customSlideSeconds?: T;
              id?: T;
              blockName?: T;
            };
        guests?:
          | T
          | {
              title?: T;
              guestsText?: T;
              customSlideSeconds?: T;
              id?: T;
              blockName?: T;
            };
        customImage?:
          | T
          | {
              image?: T;
              displayMode?: T;
              backgroundColor?: T;
              customSlideSeconds?: T;
              id?: T;
              blockName?: T;
            };
      };
  skipMembers?: T;
  transitionSound?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-pages-seo_select".
 */
export interface ListingPagesSeoSelect<T extends boolean = true> {
  site?: T;
  title?: T;
  blogPage?:
    | T
    | {
        pageTitle?: T;
        pageDescription?: T;
        seo?:
          | T
          | {
              metaTitle?: T;
              metaDescription?: T;
              keywords?: T;
              ogTitle?: T;
              ogDescription?: T;
              ogImage?: T;
              canonicalUrl?: T;
              noIndex?: T;
              noFollow?: T;
            };
      };
  eventsPage?:
    | T
    | {
        pageTitle?: T;
        pageDescription?: T;
        seo?:
          | T
          | {
              metaTitle?: T;
              metaDescription?: T;
              keywords?: T;
              ogTitle?: T;
              ogDescription?: T;
              ogImage?: T;
              canonicalUrl?: T;
              noIndex?: T;
              noFollow?: T;
            };
      };
  companiesPage?:
    | T
    | {
        pageTitle?: T;
        pageDescription?: T;
        seo?:
          | T
          | {
              metaTitle?: T;
              metaDescription?: T;
              keywords?: T;
              ogTitle?: T;
              ogDescription?: T;
              ogImage?: T;
              canonicalUrl?: T;
              noIndex?: T;
              noFollow?: T;
            };
      };
  successStoriesPage?:
    | T
    | {
        pageTitle?: T;
        pageDescription?: T;
        seo?:
          | T
          | {
              metaTitle?: T;
              metaDescription?: T;
              keywords?: T;
              ogTitle?: T;
              ogDescription?: T;
              ogImage?: T;
              canonicalUrl?: T;
              noIndex?: T;
              noFollow?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies-page-settings_select".
 */
export interface CompaniesPageSettingsSelect<T extends boolean = true> {
  site?: T;
  title?: T;
  subtitle?: T;
  description?: T;
  ctaLabel?: T;
  ctaLink?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        keywords?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        canonicalUrl?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}